import { info, warn } from "../utils/logger";
import { addLabel, createDraftPR, findExistingGuardPRs } from "../utils/github";
import { createBranch, commitAll, pushBranch } from "../utils/git";

import { PRComposition } from "./composer";

export class PRCreator {
  async create(
    composition: PRComposition,
    config: {
      owner: string;
      repo: string;
      baseBranch: string;
      token: string;
    },
  ): Promise<{ url: string; number: number } | null> {
    // Check for existing guardpr PRs with the same fingerprints
    const existingPRs = await findExistingGuardPRs(config.owner, config.repo, config.token);

    // Extract fingerprints from the composition body
    const fpMatch = /<!-- guardpr-fingerprints:(.*?) -->/.exec(composition.body);
    const newFingerprints = new Set(
      fpMatch?.[1]
        ?.split(",")
        .map((f) => f.trim())
        .filter((f) => f.length > 0) ?? [],
    );

    // Skip if there's an existing PR with the same fingerprints
    for (const existing of existingPRs) {
      const existingSet = new Set(existing.fingerprints);
      const overlap = [...newFingerprints].filter((fp) => existingSet.has(fp));
      if (overlap.length === newFingerprints.size && newFingerprints.size > 0) {
        info(`Skipping PR creation — existing PR #${existing.number} covers the same findings`);
        return null;
      }
    }

    // Create branch, commit changes, push
    await createBranch(composition.branchName);
    await commitAll(`fix(security): ${composition.title}\n\nGenerated by GuardPR`);
    await pushBranch(composition.branchName, config.token);

    // Create draft PR
    const pr = await createDraftPR({
      owner: config.owner,
      repo: config.repo,
      title: composition.title,
      body: composition.body,
      head: composition.branchName,
      base: config.baseBranch,
      token: config.token,
    });

    // Add label
    try {
      await addLabel(config.owner, config.repo, pr.number, "guardpr", config.token);
    } catch {
      warn("Failed to add guardpr label — continuing without it");
    }

    info(`Created draft PR #${pr.number}: ${pr.url}`);
    return pr;
  }
}
