import { Finding, Patch } from "../../types";

import { renderFindingCard } from "./finding-card";
import { renderSecretAlert } from "./secret-alert";

export function renderPRBody(params: {
  findings: Finding[];
  lowConfidenceFindings: Finding[];
  patches: Patch[];
  runId: number;
  sha: string;
  version: string;
}): string {
  const { findings, lowConfidenceFindings, patches, runId, sha, version } = params;

  const secretFindings = findings.filter((f) => f.category === "secrets");
  const nonSecretFindings = findings.filter((f) => f.category !== "secrets");

  const allFingerprints = [
    ...findings.map((f) => f.fingerprint),
    ...lowConfidenceFindings.map((f) => f.fingerprint),
  ];

  const lines: string[] = [];

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(
    `GuardPR detected **${findings.length}** high-confidence finding(s) and **${lowConfidenceFindings.length}** below-threshold finding(s).`,
  );
  lines.push("");

  const autoFixPatches = patches.filter((p) => p.type === "auto-fix");
  const notificationPatches = patches.filter((p) => p.type === "notification-only");
  if (autoFixPatches.length > 0) {
    lines.push(`- **Auto-fix patches**: ${autoFixPatches.length}`);
  }
  if (notificationPatches.length > 0) {
    lines.push(`- **Notification-only**: ${notificationPatches.length}`);
  }
  lines.push("");

  // Secret alert section
  if (secretFindings.length > 0) {
    lines.push(renderSecretAlert(secretFindings));
  }

  // High-confidence finding cards
  if (nonSecretFindings.length > 0) {
    lines.push("## Findings");
    lines.push("");

    for (const finding of nonSecretFindings) {
      const patch = patches.find((p) => p.findingFingerprints.includes(finding.fingerprint));
      lines.push(renderFindingCard(finding, patch));
    }
  }

  // Below-threshold findings table
  if (lowConfidenceFindings.length > 0) {
    lines.push("## Below-Threshold Findings");
    lines.push("");
    lines.push(
      "> These findings scored below the confidence threshold and are shown for informational purposes only.",
    );
    lines.push("");
    lines.push("| # | Severity | Category | File | Line | Confidence | Title |");
    lines.push("|---|----------|----------|------|------|------------|-------|");

    lowConfidenceFindings.forEach((finding, index) => {
      lines.push(
        `| ${index + 1} | ${finding.severity} | ${finding.category} | \`${finding.location.file}\` | ${finding.location.startLine} | ${(finding.confidence * 100).toFixed(0)}% | ${finding.title} |`,
      );
    });
    lines.push("");
  }

  // Review checklist
  lines.push("## Review Checklist");
  lines.push("");
  lines.push("- [ ] Verified that all auto-fix patches are correct");
  lines.push("- [ ] Checked for breaking changes in dependency upgrades");
  lines.push("- [ ] Rotated any detected secrets");
  lines.push("- [ ] Reviewed below-threshold findings for false negatives");
  lines.push("- [ ] Ran full test suite after merging");
  lines.push("");

  // Audit footer
  lines.push("---");
  lines.push("");
  lines.push(
    `<sub>Generated by [GuardPR](https://github.com/guardpr/guardpr) v${version} | Run ID: ${runId} | Commit: ${sha.slice(0, 8)}</sub>`,
  );
  lines.push("");

  // Hidden fingerprints for deduplication
  lines.push(`<!-- guardpr-fingerprints:${allFingerprints.join(",")} -->`);

  return lines.join("\n");
}
